# Generated by Django 5.2.8 on 2025-11-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='color',
            new_name='color_vehiculo',
        ),
    ]
